### ISSUE TITLE
Is this thread-safe?

### ISSUE THREAD

**Issue by psychon** [richardanaya/globals#1]
Looking at the code, I wonder what happens when two threads want to initialise the `GLOBALS_LIST` at the same time. This should result in a data race.
https://github.com/richardanaya/globals/blob/f427f1e4c93215efff5052071b71b61d70e0549c/src/lib.rs#L17-L19
I think that the size of `GLOBALS_LIST` is larger than a word, so this should even be a problem on common architectures.

**Comment by richardanaya** [comment]
@psychon hmm, thanks for your issue psychon, i'll investigate this!

**Comment by richardanaya** [comment]
switched back to lazy static
